# Site settings
title: Joy Han
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Joy Han
user_description: 你好，这里是花花~/n能看到这一行吗？
user_title: Software Freshman
email: 2362627768@qq.com
# twitter_username: Joy Han
# github_username:  Joy Han
# gplus_username:  Joy Han

exclude: ['package.json', 'src' , 'node_modules']
